### ISSUE TITLE
Install Failure  Version 4.1.3.20

### ISSUE THREAD

**Issue by codispdp** [scristalli/SQLMemo#2] opened 2016-04-11 12:53 UTC
Cannot install SQL Memo extension

java.lang.NullPointerException
    at oracle.ideimpl.webupdate.uninstall.CFUBundlesExtraInfo.extrasToString(CFUBundlesExtraInfo.java:67)
    at oracle.ideimpl.webupdate.commandline.PreInstaller.seedInstaller(PreInstaller.java:583)
    at oracle.ideimpl.webupdate.commandline.PreInstaller.commit(PreInstaller.java:131)
    at oracle.ideimpl.webupdate.wizard.UpdateWizard.commit(UpdateWizard.java:296)
    at oracle.ideimpl.webupdate.wizard.UpdateWizard.access$000(UpdateWizard.java:55)
    at oracle.ideimpl.webupdate.wizard.UpdateWizard$1.commit(UpdateWizard.java:245)
    at oracle.ide.wizard.FSMWizard.finishImpl(FSMWizard.java:978)
    at oracle.ide.wizard.FSMWizard._validateFSMState(FSMWizard.java:667)
    at oracle.ide.wizard.FSMWizard.doFinish(FSMWizard.java:355)
    at oracle.bali.ewt.wizard.BaseWizard$Action$1.run(BaseWizard.java:4069)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at oracle.javatools.internal.ui.EventQueueWrapper._dispatchEvent(EventQueueWrapper.java:169)
    at oracle.javatools.internal.ui.EventQueueWrapper.dispatchEvent(EventQueueWrapper.java:151)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
    at java.awt.Dialog.show(Dialog.java:1084)
    at java.awt.Component.show(Component.java:1673)
    at java.awt.Component.setVisible(Component.java:1625)
    at java.awt.Window.setVisible(Window.java:1014)
    at java.awt.Dialog.setVisible(Dialog.java:1005)
    at oracle.bali.ewt.wizard.WizardDialog.runDialog(WizardDialog.java:382)
    at oracle.bali.ewt.wizard.WizardDialog.runDialog(WizardDialog.java:298)
    at oracle.ide.dialogs.WizardLauncher.runDialog(WizardLauncher.java:51)
    at oracle.ideimpl.webupdate.wizard.UpdateWizard.runWizard(UpdateWizard.java:261)
    at oracle.ideimpl.webupdate.WebUpdateController.checkForUpdates(WebUpdateController.java:24)
    at oracle.ideimpl.webupdate.WebUpdateController.handleEvent(WebUpdateController.java:31)
    at oracle.ideimpl.controller.MetaClassController.handleEvent(MetaClassController.java:54)
    at oracle.ide.controller.IdeAction$ControllerDelegatingController.handleEvent(IdeAction.java:1482)
    at oracle.ide.controller.IdeAction.performAction(IdeAction.java:663)
    at oracle.ide.controller.IdeAction.actionPerformedImpl(IdeAction.java:1153)
    at oracle.ide.controller.IdeAction.actionPerformed(IdeAction.java:618)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at oracle.javatools.internal.ui.EventQueueWrapper._dispatchEvent(EventQueueWrapper.java:169)
    at oracle.javatools.internal.ui.EventQueueWrapper.dispatchEvent(EventQueueWrapper.java:151)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by scristalli** [comment] 2016-04-11 12:57
Yeah, I know the cause of this.
In SQL Developer 4.1 this line has been added:

`buf.append(update.getDescription().replaceAll(",", "&comma&"));`

The bundle description cannot be null. As soon as I have a minute I am going to fix this by updating bundle.xml.

**Comment by knilch21** [comment] 2016-04-14 05:58
Same issue here. Looking Forward to get the fix :-)

**Comment by scristalli** [comment] 2016-04-26 10:01
Fixed in 1.0.1 (just a simple XML edit). Looking forward to get your stars on the repo ;-)

**Closed as completed by scristalli** 2016-04-26 10:01 UTC
Labels: bug

**Comment by codispdp** [comment] 2016-04-26 10:55
Great thanks
